# Generated by Django 5.2.12 on 2026-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=42)),
                ('mail', models.CharField(max_length=46, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(max_length=9)),
                ('experience', models.CharField(choices=[('adventurer', 'Adventurer'), ('experienced', 'Experienced'), ('hero', 'Hero')])),
                ('dnd', models.BooleanField(default=False)),
                ('pathfinder', models.BooleanField(default=False)),
                ('cthulhu', models.BooleanField(default=False)),
                ('indie', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('none', models.BooleanField(default=True)),
                ('interests', models.TextField()),
                ('modality', models.CharField(choices=[('online', 'Online'), ('face2face', 'Face2Face'), ('mix', 'Mix')])),
                ('first_term', models.BooleanField(default=False)),
                ('second_term', models.BooleanField(default=False)),
            ],
        ),
    ]
