# Generated by Django 5.2.12 on 2026-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='none',
            field=models.BooleanField(default=False),
        ),
    ]
