# Generated by Django 5.2.12 on 2026-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_person_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=46, primary_key=True, serialize=False, unique=True),
        ),
    ]
