# Generated by Django 6.0.3 on 2026-04-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active')),
                ('genre', models.CharField(choices=[('high_fantasy', 'High Fantasy'), ('horror', 'Horror'), ('weird', 'Weird'), ('futuristic', 'Futuristic'), ('classic', 'Classic')], default='classic')),
                ('type', models.CharField(choices=[('oneshot', 'Oneshot'), ('long_term_campaign', 'Long term campaign'), ('shortie', 'Short campaign')], default='long_term_campaign')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='articles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(null=True)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('appearance', models.TextField(default='')),
                ('birth_date', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=1)),
                ('Class', models.CharField()),
                ('specie', models.CharField(default='Human', max_length=32)),
                ('biography', models.TextField()),
                ('campaign', models.ManyToManyField(blank=True, related_name='campaigns', to='articles.campaign')),
                ('category', models.ForeignKey(blank=True, default='character', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.category')),
            ],
        ),
    ]
