# Generated by Django 6.0.3 on 2026-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='articles.category')),
            ],
        ),
    ]
