# Generated by Django 6.0.3 on 2026-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='genre',
            field=models.CharField(choices=[('high_fantasy', 'High Fantasy'), ('horror', 'Horror'), ('weird', 'Weird'), ('futuristic', 'Futuristic'), ('classic', 'Classic')], default='classic'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('oneshot', 'Oneshot'), ('long_term_campaign', 'Long term campaign'), ('shortie', 'Short campaign')], default='long_term_campaign'),
        ),
    ]
