# Generated by Django 6.0.3 on 2026-03-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_campaign_genre_campaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
