# Generated by Django 6.0.3 on 2026-03-31 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('lore', 'Lore'), ('rumour', 'Rumours'), ('curiosities', 'Curiosities'), ('character', 'Characters')], max_length=32),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
                ('campaign', models.ManyToManyField(blank=True, related_name='campaigns', to='articles.campaign')),
                ('category', models.ForeignKey(blank=True, default='character', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.article')),
            ],
        ),
    ]
