# Generated by Django 6.0.3 on 2026-03-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.ForeignKey(blank=True, default='character', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.category'),
        ),
    ]
